### PR TITLE
Update Documentation for LiteEco Plugin

### PR DESCRIPTION
**Pull request by LcyDev**
This pull request updates the documentation for the LiteEco plugin to improve clarity, organization, and user-friendliness.

1. Split the large "Permission" section into a separate file (PERMISSION.md), making it easier to navigate and maintain the document.

2. Split the sections "Setup" and "Placeholder" into separate files (CONFIG.md and PLACEHOLDER.md, respectively) for improved organization and readability.

3. Updated the content of the default config file (CONFIG.md) with more relevant information and clearer instructions.

4. Improved the comments for permissions and placeholders, providing more descriptive and straightforward explanations.

5. Added more detailed descriptions for each section, giving users a better understanding of the LiteEco plugin and its features.

6. Enhanced formatting and organization for the "Translation" section, ensuring better readability and a structured approach.

7. Included detailed steps on how to contribute translations in the "Translation" section, making it easier for translators to follow the process.

8. Provided additional context and instructions in the "Contribution Guide" section for contributors using IntelliJ IDEA and Git/GitHub Desktop.

9. Addressed minor grammar and formatting issues throughout the documentation to enhance overall clarity.entation.

10. Updated the config section to provide clearer explanations, improve organization, and enhance user-friendliness.

### CODE REVIEW

**Comment by LcyDev** [comment]
@EncryptSL Please review my changes.

**Review by EncryptSL — APPROVED** [review]
Seems okay good work.

**Comment by LcyDev** [comment]
Thank you, i'm working on the config update and the translation update.

**Comment by LcyDev** [comment]
@EncryptSL could you maybe add me as a collaborator?

So I can handle the merges for you after approving my pull requests.

**Pull request merged**
