### PR TITLE
[Feature]: Add compact representations for input/output.

### PR DESCRIPTION
**Pull request by LcyDev**
* #52 ✅
 
 * Implemented compact representations for input with `validateAmount()`.
 * Implemented compact representations for output/display in `liteEco.api.formatting()`
 * Refactored repeated code for amount validation with `validateAmount()`
 * Implemented temporal translation for `format_amount_error`
 * Added config `plugin.economy.compact_display` to toggle compact representations for output.

### CODE REVIEW

**Comment by LcyDev** [comment]
imagen
imagen

There may be a problem when it rounds compact numbers for example "10.928M" to "10.93M"

However this only happens to the output, the real value is still correct.

**Comment by LcyDev** [comment]
To fix i would need to change `formatter.maximumFractionDigits`
Maybe this could be a config entry so you can calibrate the precision.
Or just change from '2' to '3' when compacting

**Comment by LcyDev** [comment]
@EncryptSL What do you think of these changes?

Sorry i made excessive commits.
Maybe i'll redo this in a new branch and do a new pull request

**Comment by EncryptSL** [comment]
Changes looks good.

**Comment by LcyDev** [comment]
Thanks, i'm working in other plugins but i'm still making changes to this one.

I will upload the new pull request of this feature soon.

**Comment by EncryptSL** [comment]
Yep no problem

**Pull request closed without merging**
