### PR TITLE
Fixing Placeholders

### PR DESCRIPTION
**Pull request by LcyDev**
* #35 ✅
 * #36 ✅

### CODE REVIEW

**Comment by LcyDev** [comment]
[Database for testing](https://www.mediafire.com/file/u5ufr53hkus9riw/database.db/file)

**File Contents**
image

**Testing**
image

**Comment by LcyDev** [comment]
Confirmed it also works with `top_balance` `top_formatted` ✅

**Comment by EncryptSL** [comment]
Btw, thanks i was first time confused from issue, because when i tested placeholders without last argument, stacktrace was similar with your issue, thanks for resolving.

**Comment by LcyDev** [comment]
No problem ^^

**Pull request merged**
